### ISSUE TITLE
Copy paste

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#11]
On hamburger banner add to bath salts: 

"Select a date & time to schedule pick up of your handmade bath salts! 

In the appointment notes add the number of bath salts you would like to order. For large orders exceeding 5 jars, contact me directly to make sure we can fulfill your order. 

You will receive an invoice detailing scheduled pick up and number of bath salts.

It's free to pick up, each jar of bath salts is $10. Payment can be made through invoice or in person day of pick up. 

Please note: allow at least 2 days to make."

**Comment by esaith** [comment]
Complete and live as of 1/26/2020
