### ISSUE TITLE
Magazine fullscreen

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#14]
make the magazine full screen?

I emailed the whole magazine to you, use that one, has updated magazine since the only online has some info moved around

**Comment by esaith** [comment]
This appears to have been a caching issue. No code updated.

**Comment by esaith** [comment]
Reopening. The magazine should go fullscreen.

**Comment by esaith** [comment]
Updated. The magazine is on its own page and requires the user to press the X-close button to go back to the other pages.
