### ISSUE TITLE
Affiliated

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#19]
Add affiliate companies to bottom of website
![Screenshot_20200106-231021_Chrome](https://user-images.githubusercontent.com/52514061/71868308-97255a00-30db-11ea-9447-00570ffd309a.jpg)

**Comment by vchica41** [comment]
Rosemira Organics
Lash Affair

**Comment by esaith** [comment]
Added Rosemire Organics and Lash Affair affiliates
