### ISSUE TITLE
Addition of lash lift

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#31]
Next banner

[Under lashes]

[Module can drop down and you can select]
     [Lash Extensions]
     [Lash Lifts] <

Lash Lifts

Lash Lift 1 hr $72
Natural lashes are curled to create longer & fuller looking lashes

Lash Lift & Tint 1.5 hrs $82
Add definition & depth to your naturally curled lashes with True Black lash tint

(Image is attached)
![20200123_180041](https://user-images.githubusercontent.com/52514061/73031862-4ae05680-3e0b-11ea-97b5-d2f1f739bad4.jpg)

**Comment by esaith** [comment]
Complete
