### ISSUE TITLE
Lash tint

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#32]
Under 
[Lashes]
[Lash Lifts]

Lash Tint Touch-Up

Lash Tint Touch-Up 
30 mins
Enhance your Lifted Lashes or even your natural lashes with True Black lash tint
$13

**Comment by vchica41** [comment]
Use this image

![20200123_181712](https://user-images.githubusercontent.com/52514061/73032284-b971e400-3e0c-11ea-97f5-b9de0c2d5a21.jpg)

**Comment by esaith** [comment]
Complete
