### ISSUE TITLE
New contact me image

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#33]
![Screenshot_20200121-003736_Gallery](https://user-images.githubusercontent.com/52514061/73032342-defeed80-3e0c-11ea-92bb-83ac18c24aea.jpg)

**Comment by vchica41** [comment]
![20200121_003723](https://user-images.githubusercontent.com/52514061/73032377-f76f0800-3e0c-11ea-9fc8-20d19df35085.jpg)

**Comment by esaith** [comment]
Updated 1/26/2020
