### ISSUE TITLE
Waxing 

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#63]
New tab under Lash Lift

Waxing

Brow wax $12    25 mins
Brow wax plus henna dye $22    35 mins
Brow henna dye $16    20mins

Shape and clean up those brows and add henna dye for definition and one less step in your makeup routine!

Henna dye lasts up to 6 weeks!

Next slide

Upper lip wax $10    20 mins
Chin wax $10    20mins
Side burns $12    20mins

Next slide

Full face
Brows, upper lip, chin, side burns
$39     1 hr

Full face + brow henna dye $49     1 hr

**Comment by vchica41** [comment]
![20200301_111331](https://user-images.githubusercontent.com/52514061/75629187-bf967580-5bad-11ea-965b-76a0ac4f2d68.jpg)

**Comment by esaith** [comment]
Added 3/1/2020
