### ISSUE TITLE
Complimentary

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#64]
Under lash extensions tab include a black and white photo of this image and the text in dark gray/white letters: Complimentary

 When you click it, it slides over to discuss 

"Everything may not apply to everyone or every session, but the allotted time is there as to not rush the amount of time needed to conduct the service."
![IMG_20200212_214836_296](https://user-images.githubusercontent.com/52514061/74404500-ac875580-4df8-11ea-89fc-834edcd0bcab.jpg)

**Comment by esaith** [comment]
Added. 3/1/2020
