### ISSUE TITLE
Grayed pics chrome issue

### ISSUE THREAD

**Issue by vchica41** [esaith/DouseSkinIssues#8]
-only chrome there is only gray that slides between
each pic on main page and magazine (see attached pics)

![Screenshot_20191230-233250_Chrome](https://user-images.githubusercontent.com/52514061/71787238-5fd38200-2fe3-11ea-9509-1225d7476b25.jpg)
![Screenshot_20191230-233130_Chrome](https://user-images.githubusercontent.com/52514061/71787241-6e219e00-2fe3-11ea-9ffb-644d5b2ee77d.jpg)

**Comment by esaith** [comment]
Appears to have been resolved. This was likely a caching issue.
